name: foundry_widget_book
description: "A showcase app for the Foundry Design System - demonstrating all components, patterns, and design tokens."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  foundry_ds:
    git:
      url: https://github.com/lfbardi-don/foundry_ds.git
      ref: main
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
